sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.sbt -name '*.lock' | xargs rm
  - find $HOME/.ivy2 -name 'ivydata-*.properties' | xargs rm

language: scala

script:
  - sbt +test

before_deploy:
  - travis_retry git clone --depth=1 $secret_git ./secret

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    condition: -e ./deploy.sh
    all_branches: true
